# Generated by Django 4.0.6 on 2022-07-06 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RagnarokDatabase', '0002_alter_mvp_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mvp',
            name='quantity',
        ),
        migrations.CreateModel(
            name='Kills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RagnarokDatabase.mvp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RagnarokDatabase.user')),
            ],
        ),
    ]
