# Generated by Django 4.0.6 on 2022-07-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RagnarokDatabase', '0003_remove_mvp_quantity_kills'),
    ]

    operations = [
        migrations.AddField(
            model_name='kills',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
