# Generated by Django 4.0.6 on 2022-07-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RagnarokDatabase', '0004_kills_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kills',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
