# Generated by Django 4.0.6 on 2022-07-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RagnarokDatabase', '0005_alter_kills_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kills',
            name='user',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
