# Generated by Django 4.0.6 on 2022-07-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RagnarokDatabase', '0011_alter_kills_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='kills',
            name='user',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
