# Generated by Django 4.0.6 on 2022-07-11 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RagnarokDatabase', '0015_alter_kills_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kills',
            name='id',
        ),
        migrations.AlterField(
            model_name='kills',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
