# Generated by Django 4.0.6 on 2022-07-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RagnarokDatabase', '0016_remove_kills_id_alter_kills_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kills',
            old_name='user',
            new_name='username',
        ),
    ]
