# Generated by Django 4.0.6 on 2022-07-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RagnarokDatabase', '0018_rename_username_kills_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kills',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
