# Generated by Django 4.0.6 on 2022-07-11 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RagnarokDatabase', '0020_alter_kills_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kills',
            old_name='user',
            new_name='username',
        ),
    ]
