# Generated by Django 4.0.6 on 2022-07-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RagnarokDatabase', '0021_rename_user_kills_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kills',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
