# Generated by Django 4.0.6 on 2022-07-11 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RagnarokDatabase', '0022_alter_kills_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kills',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RagnarokDatabase.mvp'),
        ),
    ]
