# Generated by Django 4.0.6 on 2022-07-11 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RagnarokDatabase', '0023_alter_kills_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kills',
            name='username',
        ),
        migrations.AddField(
            model_name='kills',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kills',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kills',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
