# Generated by Django 4.0.6 on 2022-07-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RagnarokDatabase', '0024_remove_kills_username_kills_id_kills_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kills',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
